version: '3.9'

services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - docker.env
    volumes:
      - sw_db:/var/lib/postgresql/data

  django:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - swapi
    env_file:
      - docker.env
    volumes:
      - .:/code
    environment:
    - PYTHONUNBUFFERED=1

  swapi:
    build:
      dockerfile: ./Dockerfile
      context: ./swapi/

volumes:
  sw_db:
